if(NOT BUILD_TESTING)
	return()
endif()

enable_testing()

set(PROJECT_BASE_TESTS_NAME ${PROJECT_NAME}-base-tests)
set(PROJECT_BASE_TESTS_OUTPUT_NAME ${PROJECT_OUTPUT_NAME}-base-tests)

add_executable(${PROJECT_BASE_TESTS_NAME}
	${SOURCE_DIR}/ball/types/base/tests.cpp
)

target_link_libraries(${PROJECT_BASE_TESTS_NAME} PRIVATE ${PROJECT_NAME})

set_target_properties(${PROJECT_BASE_TESTS_NAME} PROPERTIES
	OUTPUT_NAME ${PROJECT_BASE_TESTS_OUTPUT_NAME}

	C_EXTENSIONS OFF
	C_STANDARD 20
	C_STANDARD_REQUIRED ON

	CXX_EXTENSIONS OFF
	CXX_STANDARD 20
	CXX_STANDARD_REQUIRED ON

	CXX_SCAN_FOR_MODULES ON
)

add_test(
	NAME ${PROJECT_BASE_TESTS_NAME}
	COMMAND $<TARGET_FILE:${PROJECT_BASE_TESTS_NAME}>
)
