#ifndef _INCLUDE_BALL_TYPES_META_HPP_
#	define _INCLUDE_BALL_TYPES_META_HPP_

#	pragma once

#	include "base.h"

#	include "meta/conditional.hpp"
#	include "meta/constevaluated.hpp"
#	include "meta/decay.hpp"
#	include "meta/enableif.hpp"
#	include "meta/fibonacci.hpp"
#	include "meta/first.hpp"
#	include "meta/fixed.hpp"
#	include "meta/get.hpp"
#	include "meta/indexof.hpp"
#	include "meta/indexsequence.hpp"
#	include "meta/indextype.hpp"
#	include "meta/isclass.hpp"
#	include "meta/isclassorunion.hpp"
#	include "meta/isconst.hpp"
#	include "meta/iscopyassignable.hpp"
#	include "meta/iscopyconstructible.hpp"
#	include "meta/isdefaultconstructible.hpp"
#	include "meta/isintegral.hpp"
#	include "meta/ismemmovesafe.hpp"
#	include "meta/ismoveassignable.hpp"
#	include "meta/ismoveconstructible.hpp"
#	include "meta/ispointer.hpp"
#	include "meta/issame.hpp"
#	include "meta/isstandardlayout.hpp"
#	include "meta/istrivial.hpp"
#	include "meta/istriviallyconstructible.hpp"
#	include "meta/istriviallycopyable.hpp"
#	include "meta/istriviallydestructible.hpp"
#	include "meta/isunion.hpp"
#	include "meta/memberfunction.hpp"
#	include "meta/pack.hpp"
#	include "meta/reflectcommon.hpp"
#	include "meta/reflectdescriptor.hpp"
#	include "meta/reflectfield.hpp"
#	include "meta/reflectforeach.hpp"
#	include "meta/reflecttraits.hpp"
#	include "meta/reflectvalue.hpp"
#	include "meta/removecv.hpp"
#	include "meta/removereference.hpp"
#	include "meta/return.hpp"
#	include "meta/select.hpp"
#	include "meta/sequence.hpp"
#	include "meta/signed.hpp"
#	include "meta/size.hpp"
#	include "meta/tuple.hpp"
#	include "meta/typecount.hpp"
#	include "meta/typeinfo.hpp"
#	include "meta/unsigned.hpp"
#	include "meta/variant.hpp"
#	include "meta/vectorallocatortype.hpp"
#	include "meta/vectorviewtypes.hpp"
#	include "meta/xvalue.hpp"

#endif // !defined( _INCLUDE_BALL_TYPES_META_HPP_ )
